import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Layout/Footer';
import Header from '@/components/Layout/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="bg-primary ">
					<Header />
					<div className="py-4 px-40">{children}</div>
					<Footer />
				</main>
			</body>
		</html>
	);
}
